### ISSUE TITLE
cuda_test missing alwayslink

### ISSUE THREAD

**Issue by skyw** [bazel-contrib/rules_cuda#202]
For the reason discussed in https://github.com/bazel-contrib/rules_cuda/issues/20

`_cuda_library` inside `cuda_test` macro needs `alwayslink=True`. I don't know if there are side effects to set it by default. So filed an issue instead of a PR to add a line.

**Comment by cloudhan** [comment]
Reasonable, along with `cuda_binary`. 

But that somehow creates implication on the hidden target, will there be some harmful case if we always set `alwayslink=True`.

Or should we add it implicitly on the hidden target or explicitly on the macro so that to avoid of macro copy pasting in some edge cases?

**Comment by skyw** [comment]
I would prefer "implicitly on the hidden target" if we can do it safely. Otherwise, exposing it to the macro would do it.
Currently some work around is needed one way or another.
