### ISSUE TITLE
No matching toolchains found

### ISSUE THREAD

**Issue by wtsung** [bazel-contrib/rules_cuda#51]
I use cuda_ibrary is in my project. And add the code (http_archive,load,...) in README to the WORKSPACE file, then execute bazel build. The build report error as follows: While resolving toolchains for target xxxxx, no matching toolchains found for types @rules_cuda//cuda:toolchain_type.
And I check my CUDA_PATH is /usr/local/cuda, same as the default setting.

**Comment by cloudhan** [comment]
At the moment, you need to use `--@rules_cuda//cuda:enable=True` to enable the detected toolchains. They are disabled by default. We might change the default behavior in the future.

**Comment by wtsung** [comment]
> default



> At the moment, you need to use `--@rules_cuda//cuda:enable=True` to enable the detected toolchains. They are disabled by default. We might change the default behavior in the future.

Thanks, my problem has been solved.

**Comment by cloudhan** [comment]
`cuda_library`, analogs to `cc_library`, they don't support dynamic library, or more specifically, they can not be used to generate `.so` and `.dll` directly. Because `cuda_library` and `cc_library` are just archive all object files, so they are only capable for producing static library, or specifically, `.a` or `.lib` files, **by design**. However, you can **link** these static libraries, with whole archive linking, and use them as input to `cc_binary` to produce a dynamic library.

**Comment by wtsung** [comment]
> 



> `cuda_library`, analogs to `cc_library`, they don't support dynamic library, or more specifically, they can not be used to generate `.so` and `.dll` directly. Because `cuda_library` and `cc_library` just **archive** all object files, so they are only capable for producing static library, or specifically, `.a` or `.lib` files, **by design**. However, you can **link** these static libraries, with whole archive linking, and use them as input to `cc_binary` to produce a dynamic library.

Thanks, I understand the solution to this problem.
