### ISSUE TITLE
Wrong checksum value in v0.1.0 release notes

### ISSUE THREAD

**Issue by skyw** [bazel-contrib/rules_cuda#56]
In https://github.com/bazel-contrib/rules_cuda/releases/tag/v0.1.0
```python
http_archive(
    name = "rules_cuda",
    sha256 = "c03654f2bb3d4b8573c99f0203e8e5f48a1db94c9a1719f04993dcb90b57bc7b",
    strip_prefix = "rules_cuda-0.1.0",
    url = "https://github.com/bazel-contrib/rules_cuda/archive/refs/tags/v0.1.0.tar.gz",
)
```

bazel failed with 
```bash
Error downloading [https://github.com/bazel-contrib/rules_cuda/archive/refs/tags/v0.1.0.tar.gz] to /home/skyw/tmp/external/rules_cuda/temp16610207071206479477/v0.1.0.tar.gz: Checksum was eda69aab587954c6f83f7beb54bf5980a237fcfcaab8adb98ba5e558b99e3bbf but wanted c03654f2bb3d4b8573c99f0203e8e5f48a1db94c9a1719f04993dcb90b57bc7b
```

Manual check
```bash
>wget https://github.com/bazel-contrib/rules_cuda/archive/refs/tags/v0.1.0.tar.gz
sha256sum v0.1.0.tar.gz
eda69aab587954c6f83f7beb54bf5980a237fcfcaab8adb98ba5e558b99e3bbf  v0.1.0.tar.gz
```

**Comment by cloudhan** [comment]
@ryanleary Do you have any idea why this happens? I suspect the https://github.com/bazel-contrib/rules_cuda/blob/39be9bbe8400b278be9d10cae3dc28159e92b2c4/.github/workflows/workspace_snippet.sh#L9 produces a different tar.gz file from the github produced one.

**Comment by ryanleary** [comment]
I've done a couple experiments with this tonight. gzip does not have determinism guarantees, and there can be timestamps in the .tar that can cause non-determinism as well. I don't see documentation on the expected behavior of the `Source code .tar.gz` links from GitHub, which I assume means the .tgz can be regenerated at any time (and indeed have found some github bugs filed in random projects about the checksums changing for a static tag).

I've also noticed in the `rules_rust` and `rules_cc` repositories that they upload their own `.tgz` as a release artifact. I think we will need to do that.

**Comment by cloudhan** [comment]
https://github.com/keybase/client/issues/10800#issuecomment-375831096, not sure if it still apply nowadays.

**Comment by ryanleary** [comment]
New release addresses this: https://github.com/bazel-contrib/rules_cuda/releases/tag/v0.1.1 and is fixed going forward.
